/*********************************************************************
*            (c) 1998 - 2019 Segger Microcontroller GmbH             *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V6.16.            *
*        Compiled Nov 13 2020, 09:42:51                              *
*                                                                    *
*        (c) 1998 - 2019 Segger Microcontroller GmbH                 *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Battop                                                *
* Dimensions:  16 * 16                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
* NumBytes:    1044                                                  *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmBattop;

static GUI_CONST_STORAGE U32 _acBattop[] = {
  0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000,
  0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000,
  0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000,
  0xEB000000, 0xA7000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xBC000000, 0xFF000000, 0xFF000000,
  0x47000000, 0x9D000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0x67000000, 0xA7000000, 0xFF000000,
  0x47000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xD1000000, 0x75000000, 0xFF000000,
  0x46000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFD000000, 0xBA000000, 0xF9000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xD1000000, 0x69000000, 0xB3000000,
  0x46000000, 0xFF000000, 0xFF000000, 0xFD000000, 0xF8000000, 0xF8000000, 0xF8000000, 0x37000000, 0x13000000, 0x5C000000, 0xA8000000, 0xF0000000, 0xFF000000, 0xD1000000, 0x5D000000, 0x02000000,
  0x46000000, 0xFF000000, 0xFF000000, 0xFD000000, 0xC4000000, 0x76000000, 0x28000000, 0x01000000, 0xA2000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xD1000000, 0x5D000000, 0x02000000,
  0x46000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xD9000000, 0xD3000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xD1000000, 0x6A000000, 0xB3000000,
  0x47000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xD1000000, 0x75000000, 0xFF000000,
  0x46000000, 0x9D000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0x66000000, 0xA7000000, 0xFF000000,
  0xEB000000, 0xA7000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xA3000000, 0xBC000000, 0xFF000000, 0xFF000000,
  0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000,
  0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000,
  0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000
};

GUI_CONST_STORAGE GUI_BITMAP bmBattop = {
  16, // xSize
  16, // ySize
  64, // BytesPerLine
  32, // BitsPerPixel
  (const unsigned char *)_acBattop,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
