/*********************************************************************
*            (c) 1998 - 2019 Segger Microcontroller GmbH             *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V6.16.            *
*        Compiled Nov 13 2020, 09:42:51                              *
*                                                                    *
*        (c) 1998 - 2019 Segger Microcontroller GmbH                 *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: BattopB                                               *
* Dimensions:  16 * 16                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
* NumBytes:    1044                                                  *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmBattopB;

static GUI_CONST_STORAGE U32 _acBattopB[] = {
  0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000,
  0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000,
  0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000,
  0xEE131313, 0xAC565656, 0xA8595959, 0xA8595959, 0xA8595959, 0xA8595959, 0xA8595959, 0xA8595959, 0xA8595959, 0xA8595959, 0xA8595959, 0xA8595959, 0xA8595959, 0xC43F3F3F, 0xFF010101, 0xFF000000,
  0x50B8B8B8, 0xA1646464, 0xA75C5D5C, 0xA75C5D5C, 0xA75C5D5C, 0xA75C5D5C, 0xA75C5D5C, 0xA75C5D5C, 0xA75C5D5C, 0xA75C5D5C, 0xA75C5D5C, 0xA75C5D5C, 0xA75C5D5C, 0x699D9E9D, 0xB5525352, 0xFF000000,
  0x49B9B9B9, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xD1323232, 0x81848484, 0xFF000000,
  0x49B9B9B9, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFE030303, 0xC5414241, 0xFC050505, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xD1313131, 0x768F8F8F, 0xBF464646,
  0x49B9B9B9, 0xFF000000, 0xFF000000, 0xFF010101, 0xFE020201, 0xFE020201, 0xFE020201, 0x3BCBCBCB, 0x1EE9EAE9, 0x6B9E9F9E, 0xB9515251, 0xF90B0B0B, 0xFF000000, 0xD1313131, 0x689D9D9D, 0x0BF6F6F6,
  0x49B9B9B9, 0xFF000000, 0xFF000000, 0xFE030303, 0xCA3E3F3E, 0x7D8D8D8D, 0x2EDBDBDB, 0x03FFFFFF, 0xAD595959, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xD1313131, 0x689D9D9D, 0x0AF7F7F7,
  0x49B9B9B9, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF010101, 0xD92C2C2B, 0xD92C2C2C, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xD1313131, 0x75909090, 0xB84C4D4C,
  0x49B9B9B9, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xD1323232, 0x81848484, 0xFF000000,
  0x4DBABBBA, 0xA95C5C5C, 0xAF545554, 0xAF545554, 0xAF545554, 0xAF545554, 0xAF545554, 0xAF545554, 0xAF545554, 0xAF545554, 0xAF545554, 0xAF545554, 0xAF545554, 0x6D999999, 0xB1565656, 0xFF000000,
  0xEA181918, 0xA45E5E5E, 0xA0616161, 0xA0616161, 0xA0616161, 0xA0616161, 0xA0616161, 0xA0616161, 0xA0616161, 0xA0616161, 0xA0616161, 0xA0616161, 0xA0616161, 0xBC474747, 0xFF010101, 0xFF000000,
  0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000,
  0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000,
  0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000, 0xFF000000
};

GUI_CONST_STORAGE GUI_BITMAP bmBattopB = {
  16, // xSize
  16, // ySize
  64, // BytesPerLine
  32, // BitsPerPixel
  (const unsigned char *)_acBattopB,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
