#ifndef IMG_H_
#define IMG_H_

#include "feature_config.h"

#if 0
extern GUI_CONST_STORAGE GUI_BITMAP bmimg;
extern GUI_CONST_STORAGE GUI_BITMAP bmJoda;
extern GUI_CONST_STORAGE GUI_BITMAP bmJodaB;
extern GUI_CONST_STORAGE GUI_BITMAP bmJodaQR;
extern GUI_CONST_STORAGE GUI_BITMAP bmJodaH;
extern GUI_CONST_STORAGE GUI_BITMAP bmlemon;
extern GUI_CONST_STORAGE GUI_BITMAP bmlemonB;
extern GUI_CONST_STORAGE GUI_BITMAP bmLemonQR;
extern GUI_CONST_STORAGE GUI_BITMAP bmLemonH;
extern GUI_CONST_STORAGE GUI_BITMAP bmTel;
extern GUI_CONST_STORAGE GUI_BITMAP bmTelB;
extern GUI_CONST_STORAGE GUI_BITMAP bmTelQR;
extern GUI_CONST_STORAGE GUI_BITMAP bmTelH;
extern GUI_CONST_STORAGE GUI_BITMAP bmHydro;
extern GUI_CONST_STORAGE GUI_BITMAP bmHydroB;
extern GUI_CONST_STORAGE GUI_BITMAP bmHydroQR;
extern GUI_CONST_STORAGE GUI_BITMAP bmHydroH;

extern GUI_CONST_STORAGE GUI_BITMAP bmBatset;
extern GUI_CONST_STORAGE GUI_BITMAP bmBattop;
extern GUI_CONST_STORAGE GUI_BITMAP bmsim;
extern GUI_CONST_STORAGE GUI_BITMAP bmBTlogo;
extern GUI_CONST_STORAGE GUI_BITMAP bmpointer;
extern GUI_CONST_STORAGE GUI_BITMAP bmpointerO;

extern GUI_CONST_STORAGE GUI_BITMAP bmBatsetB;
extern GUI_CONST_STORAGE GUI_BITMAP bmBattopB;
extern GUI_CONST_STORAGE GUI_BITMAP bmsimB;
extern GUI_CONST_STORAGE GUI_BITMAP bmBTlogoB;
extern GUI_CONST_STORAGE GUI_BITMAP bmpointerB;

extern GUI_CONST_STORAGE GUI_BITMAP bmBorder;
extern GUI_CONST_STORAGE GUI_BITMAP bmBorderB;

extern GUI_CONST_STORAGE GUI_BITMAP bmline;
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmS_green_tick;
extern GUI_CONST_STORAGE GUI_BITMAP bmS_no_tick;

extern GUI_CONST_STORAGE GUI_BITMAP bmdark_blue_mask_3d;
extern GUI_CONST_STORAGE GUI_BITMAP bmdark_green_mask_3d;
extern GUI_CONST_STORAGE GUI_BITMAP bmdark_grey_mask_3d;
extern GUI_CONST_STORAGE GUI_BITMAP bmdark_red_mask_3d;
extern GUI_CONST_STORAGE GUI_BITMAP bmdark_violet_mask_3d;
extern GUI_CONST_STORAGE GUI_BITMAP bmdark_pink_mask_3d;

extern GUI_CONST_STORAGE GUI_BITMAP bmmask_kiosk;

#if (FEATURE_GUI_MARKETING_SCREEN == ENABLE_FEATURE)
extern GUI_CONST_STORAGE GUI_BITMAP bmchip2;
extern GUI_CONST_STORAGE GUI_BITMAP bmmanword2;
#endif

#endif
