/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin V5.48d.                          *
*        Compiled Sep 13 2018, 15:45:25                              *
*                                                                    *
*        (c) 1998 - 2018 Segger Microcontroller GmbH                 *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: S_no_tick                                             *
* Dimensions:  54 * 54                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmS_no_tick;

static GUI_CONST_STORAGE unsigned char _acS_no_tick[] = {
  /* RLE: 2916 Pixels @ 000,000 */ 254, 0xFF, 0xFF, 0xFF, 0x00, 254, 0xFF, 0xFF, 0xFF, 0x00, 254, 0xFF, 0xFF, 0xFF, 0x00, 254, 0xFF, 0xFF, 0xFF, 0x00, 254, 0xFF, 0xFF, 0xFF, 0x00, 254, 0xFF, 0xFF, 0xFF, 0x00, 254, 0xFF, 0xFF, 0xFF, 0x00, 
        254, 0xFF, 0xFF, 0xFF, 0x00, 254, 0xFF, 0xFF, 0xFF, 0x00, 254, 0xFF, 0xFF, 0xFF, 0x00, 254, 0xFF, 0xFF, 0xFF, 0x00, 122, 0xFF, 0xFF, 0xFF, 0x00, 
  0
};  // 60 for 2916 pixels

GUI_CONST_STORAGE GUI_BITMAP bmS_no_tick = {
  54, // xSize
  54, // ySize
  216, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)_acS_no_tick,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_RLE32
};

/*************************** End of file ****************************/
